pipelines:
 - name: pipeline_1
   steps:
     - name: step_1
       type: Bash
#        configuration:
#          inputResources:
#            - name: "myAppRepoallok11"
#            - name: "myAppRepoallok11"
       execution:
         onExecute:
           - echo $MY_MESSAGE
